window.SUMMER_CALENDAR_DATA = {
  "dataVersion": "2026-summer-xueersi-travel-v2",
  "childName": "小朋友",
  "primaryPhone": "",
  "events": [
    {
      "id": "2026-06-27-xueersi-qibao",
      "type": "course",
      "title": "学而思暑期班",
      "date": "2026-06-27",
      "start": "18:30",
      "end": "20:30",
      "leaveTime": "",
      "location": "七宝地铁站 115 教室",
      "address": "七莘路3155号",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      "id": "2026-06-28-xueersi-qibao",
      "type": "course",
      "title": "学而思暑期班",
      "date": "2026-06-28",
      "start": "18:30",
      "end": "20:30",
      "leaveTime": "",
      "location": "七宝地铁站 115 教室",
      "address": "七莘路3155号",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周三晚上。",
      "id": "2026-07-01-fitness-ganwu",
      "type": "course",
      "title": "体适能训练",
      "date": "2026-07-01",
      "start": "17:30",
      "end": "18:20",
      "location": "橄悟体育",
      "address": "橄悟体育"
    },
    {
      "id": "2026-07-04-xueersi-qibao",
      "type": "course",
      "title": "学而思暑期班",
      "date": "2026-07-04",
      "start": "18:30",
      "end": "20:30",
      "leaveTime": "",
      "location": "七宝地铁站 115 教室",
      "address": "七莘路3155号",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周日上午。",
      "id": "2026-07-05-kangaroo-math",
      "type": "course",
      "title": "袋鼠数学",
      "date": "2026-07-05",
      "start": "10:00",
      "end": "11:30",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "id": "2026-07-05-xueersi-qibao",
      "type": "course",
      "title": "学而思暑期班",
      "date": "2026-07-05",
      "start": "18:30",
      "end": "20:30",
      "leaveTime": "",
      "location": "七宝地铁站 115 教室",
      "address": "七莘路3155号",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      "id": "2026-07-06-taiyuan-depart",
      "type": "trip",
      "title": "出发去太原",
      "date": "2026-07-06",
      "start": "07:05",
      "end": "",
      "leaveTime": "",
      "location": "虹桥机场 T2",
      "address": "上海虹桥国际机场 2 号航站楼",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "航班和登机口以当天信息为准。"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周三晚上。",
      "id": "2026-07-08-fitness-ganwu",
      "type": "course",
      "title": "体适能训练",
      "date": "2026-07-08",
      "start": "17:30",
      "end": "18:20",
      "location": "橄悟体育",
      "address": "橄悟体育"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周日上午。",
      "id": "2026-07-12-kangaroo-math",
      "type": "course",
      "title": "袋鼠数学",
      "date": "2026-07-12",
      "start": "10:00",
      "end": "11:30",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周三晚上。",
      "id": "2026-07-15-fitness-ganwu",
      "type": "course",
      "title": "体适能训练",
      "date": "2026-07-15",
      "start": "17:30",
      "end": "18:20",
      "location": "橄悟体育",
      "address": "橄悟体育"
    },
    {
      "id": "2026-07-18-taiyuan-return",
      "type": "trip",
      "title": "太原回上海",
      "date": "2026-07-18",
      "start": "08:30",
      "end": "",
      "leaveTime": "",
      "location": "太原武宿 T2",
      "address": "太原武宿国际机场 2 号航站楼",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "航班和登机口以当天信息为准。"
    },
    {
      "id": "2026-07-18-xueersi-qibao",
      "type": "course",
      "title": "学而思暑期班",
      "date": "2026-07-18",
      "start": "18:30",
      "end": "20:30",
      "leaveTime": "",
      "location": "七宝地铁站 115 教室",
      "address": "七莘路3155号",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图录入。当天上午有返沪行程，请确认时间衔接。"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周日上午。",
      "id": "2026-07-19-kangaroo-math",
      "type": "course",
      "title": "袋鼠数学",
      "date": "2026-07-19",
      "start": "10:00",
      "end": "11:30",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "id": "2026-07-19-xueersi-qibao",
      "type": "course",
      "title": "学而思暑期班",
      "date": "2026-07-19",
      "start": "18:30",
      "end": "20:30",
      "leaveTime": "",
      "location": "七宝地铁站 115 教室",
      "address": "七莘路3155号",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      "id": "2026-07-22-xueersi-wanyuan",
      "type": "course",
      "title": "学而思暑期班",
      "date": "2026-07-22",
      "start": "10:30",
      "end": "12:30",
      "leaveTime": "",
      "location": "万源坊 305 教室",
      "address": "万源路550号万源坊3楼，顾戴路地铁站",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图录入。注意这两天是上午课，地点在万源坊。"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周三晚上。",
      "id": "2026-07-22-fitness-ganwu",
      "type": "course",
      "title": "体适能训练",
      "date": "2026-07-22",
      "start": "17:30",
      "end": "18:20",
      "location": "橄悟体育",
      "address": "橄悟体育"
    },
    {
      "id": "2026-07-23-xueersi-wanyuan",
      "type": "course",
      "title": "学而思暑期班",
      "date": "2026-07-23",
      "start": "10:30",
      "end": "12:30",
      "leaveTime": "",
      "location": "万源坊 305 教室",
      "address": "万源路550号万源坊3楼，顾戴路地铁站",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图录入。注意这两天是上午课，地点在万源坊。"
    },
    {
      "id": "2026-07-25-xueersi-qibao",
      "type": "course",
      "title": "学而思暑期班",
      "date": "2026-07-25",
      "start": "18:30",
      "end": "20:30",
      "leaveTime": "",
      "location": "七宝地铁站 115 教室",
      "address": "七莘路3155号",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周日上午。",
      "id": "2026-07-26-kangaroo-math",
      "type": "course",
      "title": "袋鼠数学",
      "date": "2026-07-26",
      "start": "10:00",
      "end": "11:30",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "id": "2026-07-26-xueersi-qibao",
      "type": "course",
      "title": "学而思暑期班",
      "date": "2026-07-26",
      "start": "18:30",
      "end": "20:30",
      "leaveTime": "",
      "location": "七宝地铁站 115 教室",
      "address": "七莘路3155号",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周三晚上。",
      "id": "2026-07-29-fitness-ganwu",
      "type": "course",
      "title": "体适能训练",
      "date": "2026-07-29",
      "start": "17:30",
      "end": "18:20",
      "location": "橄悟体育",
      "address": "橄悟体育"
    },
    {
      "id": "2026-08-01-yunnan-yongping-depart",
      "type": "trip",
      "title": "云南永平游学出发",
      "date": "2026-08-01",
      "start": "13:05",
      "end": "",
      "leaveTime": "",
      "location": "虹桥机场 T2",
      "address": "上海虹桥国际机场 2 号航站楼",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "航班和集合信息以当天通知为准。"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周日上午。",
      "id": "2026-08-02-kangaroo-math",
      "type": "course",
      "title": "袋鼠数学",
      "date": "2026-08-02",
      "start": "10:00",
      "end": "11:30",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周三晚上。",
      "id": "2026-08-05-fitness-ganwu",
      "type": "course",
      "title": "体适能训练",
      "date": "2026-08-05",
      "start": "17:30",
      "end": "18:20",
      "location": "橄悟体育",
      "address": "橄悟体育"
    },
    {
      "id": "2026-08-06-dali-tour",
      "type": "trip",
      "title": "游学结束返回大理游览",
      "date": "2026-08-06",
      "start": "08:30",
      "end": "",
      "leaveTime": "",
      "location": "",
      "address": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图未填写地点，后续可在管理页补充。"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周日上午。",
      "id": "2026-08-09-kangaroo-math",
      "type": "course",
      "title": "袋鼠数学",
      "date": "2026-08-09",
      "start": "10:00",
      "end": "11:30",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "id": "2026-08-09-dali-return",
      "type": "trip",
      "title": "大理回上海",
      "date": "2026-08-09",
      "start": "17:40",
      "end": "",
      "leaveTime": "",
      "location": "大理机场",
      "address": "大理凤仪机场",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "航班和登机口以当天信息为准。"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：8月游泳课。",
      "id": "2026-08-10-swim-qingpu-xiehe",
      "type": "course",
      "title": "游泳课",
      "date": "2026-08-10",
      "start": "10:00",
      "end": "11:00",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：8月游泳课。",
      "id": "2026-08-11-swim-qingpu-xiehe",
      "type": "course",
      "title": "游泳课",
      "date": "2026-08-11",
      "start": "10:00",
      "end": "11:00",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：8月游泳课。",
      "id": "2026-08-12-swim-qingpu-xiehe",
      "type": "course",
      "title": "游泳课",
      "date": "2026-08-12",
      "start": "10:00",
      "end": "11:00",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周三晚上。",
      "id": "2026-08-12-fitness-ganwu",
      "type": "course",
      "title": "体适能训练",
      "date": "2026-08-12",
      "start": "17:30",
      "end": "18:20",
      "location": "橄悟体育",
      "address": "橄悟体育"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：8月游泳课。",
      "id": "2026-08-13-swim-qingpu-xiehe",
      "type": "course",
      "title": "游泳课",
      "date": "2026-08-13",
      "start": "10:00",
      "end": "11:00",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：8月游泳课。",
      "id": "2026-08-14-swim-qingpu-xiehe",
      "type": "course",
      "title": "游泳课",
      "date": "2026-08-14",
      "start": "10:00",
      "end": "11:00",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周日上午。",
      "id": "2026-08-16-kangaroo-math",
      "type": "course",
      "title": "袋鼠数学",
      "date": "2026-08-16",
      "start": "10:00",
      "end": "11:30",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：8月游泳课。",
      "id": "2026-08-17-swim-qingpu-xiehe",
      "type": "course",
      "title": "游泳课",
      "date": "2026-08-17",
      "start": "10:00",
      "end": "11:00",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：8月游泳课。",
      "id": "2026-08-18-swim-qingpu-xiehe",
      "type": "course",
      "title": "游泳课",
      "date": "2026-08-18",
      "start": "10:00",
      "end": "11:00",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：8月游泳课。",
      "id": "2026-08-19-swim-qingpu-xiehe",
      "type": "course",
      "title": "游泳课",
      "date": "2026-08-19",
      "start": "10:00",
      "end": "11:00",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周三晚上。",
      "id": "2026-08-19-fitness-ganwu",
      "type": "course",
      "title": "体适能训练",
      "date": "2026-08-19",
      "start": "17:30",
      "end": "18:20",
      "location": "橄悟体育",
      "address": "橄悟体育"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：8月游泳课。",
      "id": "2026-08-20-swim-qingpu-xiehe",
      "type": "course",
      "title": "游泳课",
      "date": "2026-08-20",
      "start": "10:00",
      "end": "11:00",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：8月游泳课。",
      "id": "2026-08-21-swim-qingpu-xiehe",
      "type": "course",
      "title": "游泳课",
      "date": "2026-08-21",
      "start": "10:00",
      "end": "11:00",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周日上午。",
      "id": "2026-08-23-kangaroo-math",
      "type": "course",
      "title": "袋鼠数学",
      "date": "2026-08-23",
      "start": "10:00",
      "end": "11:30",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周三晚上。",
      "id": "2026-08-26-fitness-ganwu",
      "type": "course",
      "title": "体适能训练",
      "date": "2026-08-26",
      "start": "17:30",
      "end": "18:20",
      "location": "橄悟体育",
      "address": "橄悟体育"
    },
    {
      "leaveTime": "",
      "contactName": "",
      "contactPhone": "",
      "bag": [],
      "notes": "截图新增：7-8月每周日上午。",
      "id": "2026-08-30-kangaroo-math",
      "type": "course",
      "title": "袋鼠数学",
      "date": "2026-08-30",
      "start": "10:00",
      "end": "11:30",
      "location": "青浦协和校内",
      "address": "青浦协和校内"
    }
  ]
};
