window.SUMMER_CALENDAR_DATA = {
  dataVersion: "2026-summer-xueersi-travel-v1",
  childName: "小朋友",
  primaryPhone: "",
  events: [
    {
      id: "2026-06-27-xueersi-qibao",
      type: "course",
      title: "学而思暑期班",
      date: "2026-06-27",
      start: "18:30",
      end: "20:30",
      leaveTime: "",
      location: "七宝地铁站 115 教室",
      address: "七莘路3155号",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      id: "2026-06-28-xueersi-qibao",
      type: "course",
      title: "学而思暑期班",
      date: "2026-06-28",
      start: "18:30",
      end: "20:30",
      leaveTime: "",
      location: "七宝地铁站 115 教室",
      address: "七莘路3155号",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      id: "2026-07-04-xueersi-qibao",
      type: "course",
      title: "学而思暑期班",
      date: "2026-07-04",
      start: "18:30",
      end: "20:30",
      leaveTime: "",
      location: "七宝地铁站 115 教室",
      address: "七莘路3155号",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      id: "2026-07-05-xueersi-qibao",
      type: "course",
      title: "学而思暑期班",
      date: "2026-07-05",
      start: "18:30",
      end: "20:30",
      leaveTime: "",
      location: "七宝地铁站 115 教室",
      address: "七莘路3155号",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      id: "2026-07-06-taiyuan-depart",
      type: "trip",
      title: "出发去太原",
      date: "2026-07-06",
      start: "07:05",
      end: "",
      leaveTime: "",
      location: "虹桥机场 T2",
      address: "上海虹桥国际机场 2 号航站楼",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "航班和登机口以当天信息为准。"
    },
    {
      id: "2026-07-18-taiyuan-return",
      type: "trip",
      title: "太原回上海",
      date: "2026-07-18",
      start: "08:30",
      end: "",
      leaveTime: "",
      location: "太原武宿 T2",
      address: "太原武宿国际机场 2 号航站楼",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "航班和登机口以当天信息为准。"
    },
    {
      id: "2026-07-18-xueersi-qibao",
      type: "course",
      title: "学而思暑期班",
      date: "2026-07-18",
      start: "18:30",
      end: "20:30",
      leaveTime: "",
      location: "七宝地铁站 115 教室",
      address: "七莘路3155号",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "截图录入。当天上午有返沪行程，请确认时间衔接。"
    },
    {
      id: "2026-07-19-xueersi-qibao",
      type: "course",
      title: "学而思暑期班",
      date: "2026-07-19",
      start: "18:30",
      end: "20:30",
      leaveTime: "",
      location: "七宝地铁站 115 教室",
      address: "七莘路3155号",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      id: "2026-07-22-xueersi-wanyuan",
      type: "course",
      title: "学而思暑期班",
      date: "2026-07-22",
      start: "10:30",
      end: "12:30",
      leaveTime: "",
      location: "万源坊 305 教室",
      address: "万源路550号万源坊3楼，顾戴路地铁站",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "截图录入。注意这两天是上午课，地点在万源坊。"
    },
    {
      id: "2026-07-23-xueersi-wanyuan",
      type: "course",
      title: "学而思暑期班",
      date: "2026-07-23",
      start: "10:30",
      end: "12:30",
      leaveTime: "",
      location: "万源坊 305 教室",
      address: "万源路550号万源坊3楼，顾戴路地铁站",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "截图录入。注意这两天是上午课，地点在万源坊。"
    },
    {
      id: "2026-07-25-xueersi-qibao",
      type: "course",
      title: "学而思暑期班",
      date: "2026-07-25",
      start: "18:30",
      end: "20:30",
      leaveTime: "",
      location: "七宝地铁站 115 教室",
      address: "七莘路3155号",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      id: "2026-07-26-xueersi-qibao",
      type: "course",
      title: "学而思暑期班",
      date: "2026-07-26",
      start: "18:30",
      end: "20:30",
      leaveTime: "",
      location: "七宝地铁站 115 教室",
      address: "七莘路3155号",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "截图录入。建议后续补充接送联系人和建议出发时间。"
    },
    {
      id: "2026-08-01-yunnan-yongping-depart",
      type: "trip",
      title: "云南永平游学出发",
      date: "2026-08-01",
      start: "13:05",
      end: "",
      leaveTime: "",
      location: "虹桥机场 T2",
      address: "上海虹桥国际机场 2 号航站楼",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "航班和集合信息以当天通知为准。"
    },
    {
      id: "2026-08-06-dali-tour",
      type: "trip",
      title: "游学结束返回大理游览",
      date: "2026-08-06",
      start: "08:30",
      end: "",
      leaveTime: "",
      location: "",
      address: "",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "截图未填写地点，后续可在管理页补充。"
    },
    {
      id: "2026-08-09-dali-return",
      type: "trip",
      title: "大理回上海",
      date: "2026-08-09",
      start: "17:40",
      end: "",
      leaveTime: "",
      location: "大理机场",
      address: "大理凤仪机场",
      contactName: "",
      contactPhone: "",
      bag: [],
      notes: "航班和登机口以当天信息为准。"
    }
  ]
};
